mapping:
  template:
    settings:
      analysis:
        char_filter:
          configured_html_strip:
            type: html_strip
            escaped_tags: [ ]
        normalizer:
          wsnormalizer:
            type: custom
            filter:
              - trim
        filter:
          czech_stop:
            type: stop
            stopwords: _czech_
          czech_stemmer:
            type: stemmer
            language: czech
        analyzer:
          default:
            tokenizer: standard
            filter:
              - lowercase
              - czech_stop
              - czech_stemmer
